name: CI

on:
  push:
    branches: [ "main", "atlas-hub" ]
  pull_request:
    branches: [ "main", "atlas-hub" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Enable long paths
        run: git config --system core.longpaths true

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Checkout atlas-hub
        uses: actions/checkout@v4
        with:
          ref: atlas-hub
          path: atlas-hub

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Display .NET version
        run: dotnet --version

      - name: Set VERSION variable from tag
        run: echo "VERSION=0.0.0" | Out-File -FilePath $env:GITHUB_ENV

      - name: Download References - main
        shell: pwsh
        working-directory: main
        run: |
          .\Download-References.ps1

      - name: Build DLLs - Oxide (main)
        run: dotnet build Rust.UIFramework.csproj -c Release /p:Platform=Oxide /p:Version=${{ env.VERSION }} -f net48
        working-directory: main/src/Rust.UIFramework

      - name: Download References - atlas-hub
        shell: pwsh
        working-directory: atlas-hub
        run: |
          .\Download-References.ps1

      - name: Build DLLs - Oxide (atlas-hub)
        run: dotnet build Rust.UIFramework.csproj -c Release /p:Platform=UiFramework /p:Version=${{ env.VERSION }} -f net48
        working-directory: atlas-hub/src/Rust.UIFramework

      - name: Build Unit Tests - atlas-hub
        run: dotnet build src/ -c Release /p:Platform="Unit Tests"
        working-directory: atlas-hub

      - name: Run Unit Tests - atlas-hub
        run: |
            .\src\Rust.UiFramework.UnitTests\bin\"Unit Tests"\Release\net9.0\Rust.UiFramework.UnitTests.exe
        working-directory: atlas-hub
