name: Create Pre Release Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-preview.[0-9]+.[0-9]+.[0-9]"

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Checkout atlas-hub
        uses: actions/checkout@v4
        with:
          ref: atlas-hub
          path: atlas-hub

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" | Out-File -FilePath $env:GITHUB_ENV

      - name: Download References - main
        shell: pwsh
        working-directory: main
        run: |
          .\Download-References.ps1

      - name: Build DLLs - Oxide (main)
        run: dotnet build Rust.UIFramework.csproj -c Release /p:Platform=Oxide /p:Version=${{ env.VERSION }} -f net48
        working-directory: main/src/Rust.UIFramework

      - name: Download References - atlas-hub
        shell: pwsh
        working-directory: atlas-hub
        run: |
          .\Download-References.ps1

      - name: Build DLLs - Oxide (atlas-hub)
        run: dotnet build Rust.UIFramework.csproj -c Release /p:Platform=Oxide /p:Version=${{ env.VERSION }} -f net48
        working-directory: atlas-hub/src/Rust.UIFramework

      - name: Move DLLs
        run: |
          mkdir -p bin
          mv main/src/Rust.UIFramework/bin/Oxide/Release/net48/Oxide.Ext.UiFramework.dll bin/Oxide.Ext.UiFramework.dll
          mv atlas-hub/src/Rust.UIFramework/bin/Oxide/Release/net48/Oxide.Ext.UiFramework.dll bin/atlas-hub_Oxide.Ext.UiFramework.dll

      - name: Upload Release Assets
        run: |
          $TAG=($env:GITHUB_REF -replace 'refs/tags/', '')
          $dllPath = Get-ChildItem -Path bin -Filter *.dll -File | Select-Object -ExpandProperty FullName
          gh release upload $TAG $dllPath -R ${{ github.repository }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
